version: '3.8'

services:

  web:
    image: "nginx:stable-alpine"
    volumes:
      - ./src:/var/www/laravel
      - ./_docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    container_name: project_web

  app:
    build:
          context: _docker/dockerfiles
          dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/laravel
      - ./_docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
        - db
    container_name: project_app

  db:
      image: postgres:14.3-alpine
      restart: always
      volumes:
          - ./tmp/db:/var/lib/postgresql/data
      env_file:
        - _docker/env/pgsql.env
      ports:
          - "5435:5432"
      container_name: project_db

  composer:
    build:
      context: _docker/dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build:
      context: _docker/dockerfiles
      dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php","/var/www/laravel/artisan"]